name: Install LLVM
description: Install a specific version of LLVM
author: paulhuggett
inputs:
  version:
    description: The version number of LLVM to be installed
    default: 16
    required: true

outputs:
  success:
    value: true
    description: Returns `"true"` if the installation was successful

runs:
  using: composite
  steps:
    - id: branch
      if: ${{ runner.os }} == 'Linux'
      env:
        INPUTS_VERSION: ${{ inputs.version }}
        SCRIPT: /tmp/llvm.sh
      shell: bash
      run: |
        ls -l
        # Force --yes to the end of the add-apt-repository command to
        # prevent the llvm.sh script hanging.
        sed -ie "/^add-apt-repository/ s/$/ --yes/" "$SCRIPT"
        chmod +x "$SCRIPT"
        sudo "$SCRIPT" "$INPUTS_VERSION"

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding

#branding:
#  icon: download
#  color: green
