name: Install LLVM
description: Install a specific version of LLVM
author: paulhuggett

inputs:
  version:
    description: The version number of LLVM to be installed
    required: true

  all:
    description: Install all packages?
    default: false
    required: false

  code-name:
    description: Specifies the distro codename, for example bionic
    required: false

  repo-base-url:
    description: Specifies the base URL from which to download
    required: false

runs:
  using: composite
  steps:
    - name: Install LLVM
      if: ${{ runner.os }} == 'Linux'
      shell: bash
      run: |
        options=""
        all=$(echo ${{ inputs.all }} | tr '[:upper:]' '[:lower:]')
        if [ "$all" == 'true' ]; then
          options="$options all"
        fi
        if [ -n "${{ inputs.code-name }}" ]; then
          options="$options -n='${{ inputs.code-name }}'"
        fi
        if [ -n "${{ inputs.repo-base-url }}" ]; then
          options="$options -m='${{ inputs.repo-base-url }}'"
        fi

        SCRIPT="$GITHUB_ACTION_PATH/llvm.sh"
        # Force --yes to the end of the add-apt-repository command to
        # prevent the llvm.sh script hanging.
        sed -ie "/^add-apt-repository/ s/$/ --yes/" "$SCRIPT"
        chmod +x "$SCRIPT"

        sudo "$SCRIPT" "${{ inputs.version }}" $options

branding:
  icon: download
  color: blue
