name: Install LLVM
description: Install a specific version of LLVM
author: paulhugget
inputs:
  version:
    description: The version number of LLVM to be installed
    default: 16
    required: true

outputs:
  success:
    value: true
    description: Returns `"true"` if the installation was successful

runs:
  using: composite
  steps:
    - id: branch
      env:
        INPUTS_VERSION: ${{ inputs.version }}
      shell: bash
      run: |
          wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh
          # Force --yes to the end of the add-apt-repository command to
          # prevent the llvm.sh script hanging.
          sed -ie "/^add-apt-repository/ s/$/ --yes/" /tmp/llvm.sh
          chmod +x llvm.sh
          sudo /tmp/llvm.sh "$INPUTS_VERSiON"

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding

#branding:
#  icon: download
#  color: green
